### ISSUE TITLE
number of POIs with SubmissionStatusTypeID for delisted entries seems quite high

### ISSUE THREAD

**Issue by mainrs** [openchargemap/ocm-data#3]
I've downloaded the gzipped JSON file and done some basic filtering using pandas. Filtering out all delisted POIs (1000, 1001, 1005, 1010, 1020) results in only 40616 entries left that are flagged as being live (from 135952 total entries). The website lists all stations available per country at https://openchargemap.org/site/country. Adding those numbers up results in way more stations than I have filtered out (the same goes for locations).

Maybe I am just understanding the field wrong though. Or does the website display delisted stations as well?

On a side note, is this the complete database dump? Or just recently cached values based on access by users?

**Comment by webprofusion-chrisc** [comment]
Hi, a submission status type id of 100 or 200 indicates a live POI, you should have 93272 unless there is something wrong with the data dump (which there could be!). The data dump is an export of a MongoDB cache of our database which in turn is synced from our master API. If there is actually data missing it could be the sync is wrong.

I'm pushed for time right now but I'll investigate when I get a chance.

**Comment by mainrs** [comment]
Just filtered for 100 and 200. I got 93534 POIs. Not sure why the number of POIs is so low when I do it the other way around.

I got a question about the data format though. Inside the `Connections` array are all outlet connections listed that are available alongside a `Quantity` field. Is there some way to differentiate between a POI that has two outlets of type X and a POI that has two stations with one outlet of type X each? I would assume a row inside the poi.json file is one single station. If that is true, how are stations handled that are at the same location and have the same address? If that is the case, there seems to be only 6 AddressInfoIDs that are used more than once (although it might be that the only difference are the coords, which would technically result in locations with the same ID but different coords and therefore a different ID).

I did pick a random POI and it looked like the `Quantity` field (in that example) has been used to denote the number of stations. Often enough, a user comment is in-place telling how many stations are there. As far as I can tell there is no easy way to extract this information. Is that right?

**Comment by webprofusion-chrisc** [comment]
No, I don't think we have it they way you expect to see it - we currently don't have a station level grouping of equipment, historically this is because the data we imported often didn't have that information available (i.e. "this site has 2x J1772" available could mean two stations or one station with two connectors). We still plan to add that capability (grouping connectors into stations) but there's no way to migrate the data to that as we just don't have the information.

The top level NumberOfPoints field is a misnomer and should mean number of bays/stations i.e. how many vehicles can charge here at one time. Connection Quantity is an optional aggregation  and means there are N connectors of this type at this site. User populating the data could optionally list the same connector type twice to convey two stations but it's not defined.

**Comment by mainrs** [comment]
Thanks for the explanation. So my best bet would be to take a look at the `NumberOfPoints` field, am I right? Although some stations do allow two vehicles to charge simultaneously, it is the closest I can get to "true stations".

**Comment by webprofusion-chrisc** [comment]
It depends what you're trying to do but I'm guess you want to know total number of stations so yes the closest would be the sum of NumberOfPoints (if null, then assume 1). 

One of the challenges of being crowdsourced (with some imported data) is we're wrangling a whole jumble of information into one source, with varying data quality. The real data improvement comes when users on the ground making edits, so when people use the data we ask that they link back to the source so that people can make corrections.

**Comment by mainrs** [comment]
Thanks for helping me out! I've got another question if you do not mind. The geo coordinates that are linked to each table row, are they being normalized into the same coordinate reference system (CRS) before imported into the database? Or are they just taken as is from the user input or data source and saved? 

Depending on which CRS is being used, the coordinates can actually point to different locations :)

**Comment by webprofusion-chrisc** [comment]
It's not stated anywhere but you can assume all data is EPSG:3857 (WGS 84)  https://epsg.io/3857 - and if any data doesn't conform to that then it needs fixed.
