### ISSUE TITLE
OCM Import file from Guil.cl / Evsy.

### ISSUE THREAD

**Issue by jmarquez82** [openchargemap/ocm-data#8]
- Guil.cl / Evsy  import file
- Massive data loading.
- It only contains public residences.

Contact:
diego.larrain@guil.cl
jmarquez@dev21.cl

I await your validation or confirmation.

Greetings.

[ocm_import_v1.xlsx](https://github.com/openchargemap/ocm-data/files/6609831/ocm_import_v1.xlsx)

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for this, please can you :
- confirm where the data originates from and that we have explicit permission to redistribute it as https://creativecommons.org/licenses/by-sa/4.0/ ? We would need at least an email from the data owner saying we can use this data freely under our own license to `info at openchargemap.org` 
- I note this is a mix of operators (Enel X and Copec Voltex), if you don't own the data please submit POIs individually as your own work ensuring no data is directly copied.
- Latitude and Longitudes are formatted as integers but should be decimal. Please change them to be decimals eg 33.333 instead of 33333
- Connection Type names must match our (english) reference data names for an import to work - see the Connection Type list at https://openchargemap.org/site/poi
- Power (kw) should just be a number (eg. 50), not "50 kwh"
- Connection4_Quantity is populated with "1" in each row, this should be blank if not used.

Note that if any of these locations are a close duplicate (position) of data we already have they will not be imported and instead you would need to update the existing listing.

**Comment by webprofusion-chrisc** [comment]
It's worth also noting that it would take approximately 3 hrs to just enter these manually using https://map.openchargemap.io (especially using the Copy Equipment feature)  - so it's not always worth spending a lot of time preparing the import data. Diego is a marked as a Country Editor for Chile, so his edits will appear quickly.
